<?php
/**
 * Generates README documentation.
 *
 * @package AABG
 */

namespace AABG\Generator;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class README_Generator
 */
class README_Generator {

	/**
	 * Generate README.md content.
	 *
	 * @param array $spec Block specification.
	 * @return string
	 */
	public function generate( $spec ) {
		$slug    = $spec['block_slug'] ?? 'custom-block';
		$title   = $spec['block_name'] ?? ucwords( str_replace( '-', ' ', $slug ) );
		$fields  = $spec['fields'] ?? array();
		$suggest = $spec['suggestions'] ?? array();

		$md  = "# {$title}\n\n";
		$md .= "> Generated by AI ACF Block Generator\n\n";
		$md .= "## Description\n\n";
		$md .= ( $spec['block_description'] ?? $spec['purpose'] ?? 'ACF Gutenberg Block' ) . "\n\n";
		$md .= "## Block Slug\n\n";
		$md .= "`acf/{$slug}`\n\n";
		$md .= "## Layout\n\n";
		$md .= "- **Type:** " . ( $spec['layout'] ?? 'content' ) . "\n";
		$md .= "- **Details:** " . ( $spec['layout_details'] ?? 'Standard layout' ) . "\n\n";

		$md .= "## ACF Fields\n\n";
		$md .= "| Label | Name | Type |\n";
		$md .= "|-------|------|------|\n";

		foreach ( $fields as $field ) {
			$md .= sprintf(
				"| %s | `%s` | %s |\n",
				$field['label'] ?? '',
				$field['name'] ?? '',
				$field['type'] ?? 'text'
			);

			if ( ! empty( $field['sub_fields'] ) ) {
				foreach ( $field['sub_fields'] as $sub ) {
					$md .= sprintf(
						"| ↳ %s | `%s` | %s |\n",
						$sub['label'] ?? '',
						$sub['name'] ?? '',
						$sub['type'] ?? 'text'
					);
				}
			}
		}

		$md .= "\n## Files\n\n";
		$md .= "- `block.json` — Block registration\n";
		$md .= "- `render.php` — Frontend template\n";
		$md .= "- `fields.json` — ACF field group\n";
		$md .= "- `style.css` — Frontend styles\n";
		$md .= "- `editor.css` — Editor styles\n";

		if ( ! empty( $spec['needs_javascript'] ) ) {
			$md .= "- `script.js` — Frontend JavaScript ({$spec['javascript_type']})\n";
		}

		$md .= "- `editor.js` — Editor JavaScript\n";
		$md .= "- `preview.png` — Block preview placeholder\n\n";

		if ( ! empty( $suggest ) ) {
			$md .= "## AI Suggestions\n\n";

			if ( ! empty( $suggest['accessibility'] ) ) {
				$md .= "### Accessibility\n\n";
				foreach ( $suggest['accessibility'] as $tip ) {
					$md .= "- {$tip}\n";
				}
				$md .= "\n";
			}

			if ( ! empty( $suggest['performance'] ) ) {
				$md .= "### Performance\n\n";
				foreach ( $suggest['performance'] as $tip ) {
					$md .= "- {$tip}\n";
				}
				$md .= "\n";
			}

			if ( ! empty( $suggest['reusable_groups'] ) ) {
				$md .= "### Reusable Field Groups\n\n";
				foreach ( $suggest['reusable_groups'] as $tip ) {
					$md .= "- {$tip}\n";
				}
				$md .= "\n";
			}
		}

		$md .= "## Usage\n\n";
		$md .= "This block is automatically registered when the AI ACF Block Generator plugin is active.\n";
		$md .= "Find it in the block inserter under **" . ( $spec['block_category'] ?? 'custom-blocks' ) . "**.\n";

		return $md;
	}
}
