<?php
/**
 * Generates theme-compatible SCSS component files.
 *
 * @package AABG
 */

namespace AABG\Generator;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Theme_SCSS_Generator
 */
class Theme_SCSS_Generator {

	/**
	 * Generate SCSS for theme components folder.
	 *
	 * @param array $spec Block specification.
	 * @return string
	 */
	public function generate( $spec ) {
		$slug   = $spec['block_slug'] ?? 'custom-block';
		$bem    = $this->get_component_class( $spec );
		$layout = $spec['layout'] ?? 'content';
		$design = $spec['design_tokens'] ?? array();

		$primary = $design['primary_color'] ?? '$primary-100';
		$text    = $design['text_color'] ?? '$body-color';
		$bg      = $design['background_color'] ?? '$body-bg';
		$gap     = $design['gap'] ?? '1.5rem';
		$heading = $design['heading_size'] ?? '2.5rem';

		$primary_raw = $design['primary_color'] ?? '';
		$bg_raw      = $design['background_color'] ?? '';
		$text_raw    = $design['text_color'] ?? '';

		$scss  = "@use \"@scss/abstracts/variables\" as *;\n";
		$scss .= "@use \"@scss/abstracts/function\" as *;\n";
		$scss .= "@use \"@scss/abstracts/mixins\" as *;\n\n";
		$scss .= "/**\n";
		$scss .= " * {$slug} block styles\n";
		$scss .= " * Generated by AI ACF Block Generator\n";
		$scss .= " */\n\n";

		$scss .= ".{$bem} {\n";
		$scss .= "\tposition: relative;\n";
		$scss .= "\twidth: 100%;\n";
		$scss .= "\tpadding: var(--space-lg, #{rem(64)}) 0;\n";

		if ( $bg_raw ) {
			$scss .= "\tbackground-color: {$bg_raw};\n";
		} else {
			$scss .= "\tbackground-color: {$bg};\n";
		}

		if ( $text_raw ) {
			$scss .= "\tcolor: {$text_raw};\n";
		} else {
			$scss .= "\tcolor: {$text};\n";
		}

		if ( $primary_raw || $bg_raw || $text_raw ) {
			$scss .= "\n";
			if ( $primary_raw ) {
				$scss .= "\t--block-primary: {$primary_raw};\n";
			}
			if ( $bg_raw ) {
				$scss .= "\t--block-bg: {$bg_raw};\n";
			}
			if ( $text_raw ) {
				$scss .= "\t--block-text: {$text_raw};\n";
			}
			$scss .= "\t--row-gap: {$gap};\n";
		}

		$scss .= "\n";
		$scss .= "\t.container {\n";
		$scss .= "\t\t--container-width: #{\$container-width};\n";
		$scss .= "\t}\n\n";

		$scss .= "\t&__content,\n";
		$scss .= "\t&__media {\n";
		$scss .= "\t\tdisplay: flex;\n";
		$scss .= "\t\tflex-direction: column;\n";
		$scss .= "\t\tgap: {$gap};\n";
		$scss .= "\t}\n\n";

		$scss .= "\t&__row {\n";
		$scss .= "\t\tdisplay: flex;\n";
		$scss .= "\t\tflex-direction: column;\n";
		$scss .= "\t\tgap: var(--row-gap, {$gap});\n";
		$scss .= "\t\twidth: 100%;\n\n";
		$scss .= "\t\t@include respond-above('md') {\n";
		$scss .= "\t\t\tflex-direction: row;\n";
		$scss .= "\t\t\talign-items: center;\n";
		$scss .= "\t\t}\n";
		$scss .= "\t}\n\n";

		$scss .= "\t&__col {\n";
		$scss .= "\t\twidth: 100%;\n\n";
		$scss .= "\t\t@include respond-above('md') {\n";
		$scss .= "\t\t\twidth: var(--col-width, 50%);\n";
		$scss .= "\t\t\tflex: 0 0 var(--col-width, 50%);\n";
		$scss .= "\t\t}\n";
		$scss .= "\t}\n\n";

		$scss .= "\t&__col--col-media {\n";
		$scss .= "\t\t@include respond-above('md') {\n";
		$scss .= "\t\t\torder: 2;\n";
		$scss .= "\t\t}\n";
		$scss .= "\t}\n\n";

		$scss .= "\t&__inner {\n";
		$scss .= "\t\tdisplay: flex;\n";
		$scss .= "\t\tflex-direction: column;\n";
		$scss .= "\t\tgap: {$gap};\n";
		$scss .= "\t}\n\n";

		$structure = $spec['layout_structure']['rows'] ?? array();
		if ( empty( $structure ) && in_array( $layout, array( 'hero', 'two-column' ), true ) ) {
			$scss .= "\t@include respond-above('md') {\n";
			$scss .= "\t\t&__inner {\n";
			$scss .= "\t\t\tflex-direction: row;\n";
			$scss .= "\t\t\talign-items: center;\n";
			$scss .= "\t\t}\n";
			$scss .= "\t}\n\n";
		}

		if ( ! empty( $structure ) ) {
			$seen_cols = array();
			foreach ( $structure as $row ) {
				foreach ( $row['columns'] ?? array() as $column ) {
					$col_class = ! empty( $column['class'] ) ? sanitize_html_class( $column['class'] ) : 'col';
					if ( isset( $seen_cols[ $col_class ] ) ) {
						continue;
					}
					$seen_cols[ $col_class ] = true;
					if ( ! empty( $column['width'] ) && '100%' !== $column['width'] ) {
						$scss .= "\t&__col--{$col_class} {\n";
						$scss .= "\t\t--col-width: {$column['width']};\n";
						$scss .= "\t}\n\n";
					}
				}
			}
		}

		if ( 'slider' === $layout ) {
			$scss .= "\t&__slider {\n";
			$scss .= "\t\toverflow: hidden;\n";
			$scss .= "\t}\n\n";
			$scss .= "\t&__slide {\n";
			$scss .= "\t\ttext-align: center;\n";
			$scss .= "\t\tpadding: #{rem(16)};\n";
			$scss .= "\t}\n\n";
		}

		$scss .= "\t&__heading,\n";
		$scss .= "\t&__title {\n";
		$scss .= "\t\tmargin: 0 0 #{rem(8)};\n";
		$scss .= "\t\t@include hgroup;\n";
		$scss .= "\t\tfont-size: clamp(#{rem(28)}, 4vw, #{rem(40)});\n";
		if ( $heading && is_numeric( str_replace( array( 'rem', 'px' ), '', $heading ) ) ) {
			$scss .= "\t\tfont-size: clamp(#{rem(28)}, 4vw, {$heading});\n";
		}
		$scss .= "\t}\n\n";

		$scss .= "\t&__subtitle {\n";
		$scss .= "\t\tmargin: 0 0 #{rem(16)};\n";
		$scss .= "\t\tfont-size: clamp(#{rem(18)}, 2.5vw, #{rem(24)});\n";
		$scss .= "\t}\n\n";

		$scss .= "\t&__description {\n";
		$scss .= "\t\tmargin-bottom: #{rem(24)};\n";
		$scss .= "\t\tline-height: 1.6;\n";
		$scss .= "\t}\n\n";

		$scss .= "\t&__image {\n";
		$scss .= "\t\tposition: relative;\n";
		$scss .= "\t\tborder-radius: #{rem(8)};\n";
		$scss .= "\t\toverflow: hidden;\n\n";
		$scss .= "\t\timg {\n";
		$scss .= "\t\t\twidth: 100%;\n";
		$scss .= "\t\t\theight: auto;\n";
		$scss .= "\t\t\tdisplay: block;\n";
		$scss .= "\t\t\tobject-fit: cover;\n";
		$scss .= "\t\t}\n";
		$scss .= "\t}\n\n";

		$scss .= "\t&__button {\n";
		if ( $primary_raw ) {
			$scss .= "\t\tbackground: var(--block-primary, {$primary_raw});\n";
		} elseif ( '$' === substr( $primary, 0, 1 ) ) {
			$scss .= "\t\tbackground: {$primary};\n";
		} else {
			$scss .= "\t\tbackground: {$primary};\n";
		}
		$scss .= "\t\tcolor: \$white;\n";
		$scss .= "\t}\n";
		$scss .= "}\n";

		return $scss;
	}

	/**
	 * Get BEM root class for component.
	 *
	 * @param array $spec Spec.
	 * @return string
	 */
	private function get_component_class( $spec ) {
		$slug = $spec['block_slug'] ?? 'block';
		return $slug . '-component';
	}
}
