<?php
/**
 * Generates compiled plain CSS for theme blocks (no npm required).
 *
 * The output is scoped entirely under the block's component class so it can
 * never leak into the rest of the theme. It is also self-sufficient: correct
 * grid widths, repeater grids and design tokens are emitted directly, so the
 * block renders correctly even where the theme grid CSS is unavailable
 * (for example inside the block editor preview).
 *
 * @package AABG
 */

namespace AABG\Generator;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Theme_CSS_Generator
 */
class Theme_CSS_Generator {

	/**
	 * Breakpoint map for responsive cell classes (min-width in px).
	 *
	 * @var array
	 */
	private $breakpoints = array(
		'sm' => 576,
		'md' => 768,
		'lg' => 1024,
		'xl' => 1280,
	);

	/**
	 * Generate frontend CSS for a block.
	 *
	 * @param array $spec Block specification.
	 * @return string
	 */
	public function generate( $spec ) {
		$slug   = $spec['block_slug'] ?? 'custom-block';
		$bem    = $slug . '-component';
		$layout = $spec['layout'] ?? 'content';
		$fields = $spec['fields'] ?? array();
		$design = is_array( $spec['design_tokens'] ?? null ) ? $spec['design_tokens'] : array();

		$t = $this->tokens( $design );

		$css  = "/**\n * {$slug} block — compiled CSS.\n * Generated by AI ACF Block Generator.\n */\n\n";

		// Design tokens as scoped custom properties (easy client overrides).
		$css .= ".{$bem} {\n";
		$css .= "  --block-primary: {$t['primary']};\n";
		$css .= "  --block-text: {$t['text']};\n";
		$css .= "  --block-bg: {$t['bg']};\n";
		$css .= "  --block-gap: {$t['gap']};\n";
		$css .= "  --block-radius: {$t['radius']};\n";
		$css .= "  position: relative;\n";
		$css .= "  width: 100%;\n";
		$css .= "  padding: {$t['padding']};\n";
		$css .= "  background-color: var(--block-bg);\n";
		$css .= "  color: var(--block-text);\n";
		$css .= "}\n\n";

		$css .= $this->grid_css( $bem, $spec );
		$css .= $this->flow_css( $bem, $t );
		$css .= $this->typography_css( $bem, $t );
		$css .= $this->media_css( $bem, $t );
		$css .= $this->button_css( $bem, $t );

		if ( $this->has_repeater( $fields ) || in_array( $layout, array( 'grid', 'cards', 'features', 'team', 'testimonial' ), true ) ) {
			$css .= $this->repeater_css( $bem, $t );
		}

		if ( 'slider' === $layout ) {
			$css .= $this->slider_css( $bem, $t );
		}

		if ( 'accordion' === $layout ) {
			$css .= $this->accordion_css( $bem, $t );
		}

		$css .= ".{$bem} .text-center { text-align: center; }\n";

		return $css;
	}

	/**
	 * Normalise design tokens with sensible fallbacks.
	 *
	 * @param array $design Raw design tokens.
	 * @return array
	 */
	private function tokens( $design ) {
		$gap = $this->css_value( $design['gap'] ?? '', '1.5rem' );

		return array(
			'primary' => $this->css_color( $design['primary_color'] ?? '', '#2271b1' ),
			'text'    => $this->css_color( $design['text_color'] ?? '', '#1d2327' ),
			'bg'      => $this->css_color( $design['background_color'] ?? '', '#ffffff' ),
			'accent'  => $this->css_color( $design['accent_color'] ?? ( $design['primary_color'] ?? '' ), '#32CD32' ),
			'gap'     => $gap,
			'radius'  => $this->css_value( $design['radius'] ?? '', '8px' ),
			'padding' => $this->css_value( $design['section_padding'] ?? '', '4rem 0' ),
			'heading' => $this->css_value( $design['heading_size'] ?? '', 'clamp(1.75rem, 4vw, 2.5rem)' ),
		);
	}

	/**
	 * Build grid / container / cell CSS from the layout structure.
	 *
	 * @param string $bem  Component class.
	 * @param array  $spec Block spec.
	 * @return string
	 */
	private function grid_css( $bem, $spec ) {
		$css  = ".{$bem} .container {\n";
		$css .= "  width: min(100% - 40px, 1170px);\n";
		$css .= "  margin-inline: auto;\n";
		$css .= "}\n\n";

		$css .= ".{$bem} .row {\n";
		$css .= "  display: flex;\n";
		$css .= "  flex-wrap: wrap;\n";
		$css .= "  margin-inline: -15px;\n";
		$css .= "  row-gap: var(--block-gap);\n";
		$css .= "}\n\n";

		$css .= ".{$bem} .row.align-items-center { align-items: center; }\n";
		$css .= ".{$bem} .row.align-items-start { align-items: flex-start; }\n";
		$css .= ".{$bem} .row.align-items-end { align-items: flex-end; }\n\n";

		$css .= ".{$bem} [class*=\"cell-\"] {\n";
		$css .= "  position: relative;\n";
		$css .= "  width: 100%;\n";
		$css .= "  padding-inline: 15px;\n";
		$css .= "  box-sizing: border-box;\n";
		$css .= "}\n\n";

		// Correct per-cell widths derived from the theme's 12-column system,
		// scoped so they match the design instead of forcing everything to 50%.
		$cells = $this->collect_cell_classes( $spec );
		$css  .= $this->cell_width_css( $bem, $cells );

		// BEM column fallback (grid_system: "bem").
		$css .= ".{$bem}__row {\n";
		$css .= "  display: flex;\n";
		$css .= "  flex-direction: column;\n";
		$css .= "  gap: var(--block-gap);\n";
		$css .= "  width: 100%;\n";
		$css .= "}\n";
		$css .= ".{$bem}__col { width: 100%; }\n\n";

		$has_two_col = $this->structure_has_multiple_columns( $spec )
			|| in_array( $spec['layout'] ?? '', array( 'hero', 'two-column' ), true );

		if ( $has_two_col ) {
			$css .= "@media (min-width: 768px) {\n";
			$css .= "  .{$bem}__row { flex-direction: row; align-items: center; }\n";
			$css .= "  .{$bem}__col { width: var(--col-width, 50%); flex: 0 0 var(--col-width, 50%); }\n";
			$css .= "  .{$bem}__col--col-media { order: 2; }\n";
			$css .= "  .{$bem}__inner { flex-direction: row; align-items: center; }\n";
			$css .= "}\n\n";
		}

		// Explicit BEM column widths from structure.
		foreach ( $spec['layout_structure']['rows'] ?? array() as $row ) {
			foreach ( $row['columns'] ?? array() as $column ) {
				$col_class = ! empty( $column['class'] ) ? sanitize_html_class( $column['class'] ) : '';
				$width     = $column['width'] ?? '';
				if ( $col_class && $width && '100%' !== $width ) {
					$css .= "@media (min-width: 768px) {\n";
					$css .= "  .{$bem}__col--{$col_class} { --col-width: {$width}; }\n";
					$css .= "}\n";
				}
			}
		}

		return $css . "\n";
	}

	/**
	 * Emit correct responsive widths for the cell classes in use.
	 *
	 * @param string $bem   Component class.
	 * @param array  $cells Cell class names.
	 * @return string
	 */
	private function cell_width_css( $bem, $cells ) {
		if ( empty( $cells ) ) {
			$cells = array( 'cell-12', 'cell-md-6' );
		}

		$base   = array();
		$bybp   = array();

		foreach ( $cells as $cell ) {
			$parsed = $this->parse_cell_class( $cell );
			if ( ! $parsed ) {
				continue;
			}

			$rule = "  .{$bem} .{$cell} { width: {$parsed['width']}; flex: 0 0 {$parsed['width']}; }\n";

			if ( '' === $parsed['bp'] ) {
				$base[ $cell ] = "  .{$bem} .{$cell} { width: {$parsed['width']}; }\n";
			} else {
				$min                  = $this->breakpoints[ $parsed['bp'] ];
				$bybp[ $min ]         = $bybp[ $min ] ?? array();
				$bybp[ $min ][ $cell ] = $rule;
			}
		}

		$css = '';

		foreach ( $base as $rule ) {
			$css .= $rule;
		}

		ksort( $bybp );
		foreach ( $bybp as $min => $rules ) {
			$css .= "@media (min-width: {$min}px) {\n";
			foreach ( $rules as $rule ) {
				$css .= $rule;
			}
			$css .= "}\n";
		}

		return $css . "\n";
	}

	/**
	 * Parse a cell class into breakpoint + width.
	 *
	 * @param string $cell Cell class (e.g. cell-md-6).
	 * @return array|null
	 */
	private function parse_cell_class( $cell ) {
		if ( ! preg_match( '/^cell-(?:([a-z]{2})-)?(\d{1,2})$/', $cell, $m ) ) {
			return null;
		}

		$bp  = $m[1] ?? '';
		$num = (int) $m[2];

		if ( $num < 1 || $num > 12 ) {
			return null;
		}

		if ( '' !== $bp && ! isset( $this->breakpoints[ $bp ] ) ) {
			return null;
		}

		$width = round( ( $num / 12 ) * 100, 4 );
		// Format with fixed decimals first, then trim only fractional trailing
		// zeros. Trimming the raw string ("100") would wrongly strip whole-number
		// zeros (turning 100 into 1, 50 into 5), collapsing every column.
		$width = rtrim( rtrim( number_format( $width, 4, '.', '' ), '0' ), '.' ) . '%';

		return array(
			'bp'    => $bp,
			'width' => $width,
		);
	}

	/**
	 * Flow containers (content / media / inner).
	 *
	 * @param string $bem Component class.
	 * @param array  $t   Tokens.
	 * @return string
	 */
	private function flow_css( $bem, $t ) {
		$css  = ".{$bem}__content,\n.{$bem}__media,\n.{$bem}__inner {\n";
		$css .= "  display: flex;\n";
		$css .= "  flex-direction: column;\n";
		$css .= "  gap: var(--block-gap);\n";
		$css .= "}\n\n";

		return $css;
	}

	/**
	 * Typography CSS.
	 *
	 * @param string $bem Component class.
	 * @param array  $t   Tokens.
	 * @return string
	 */
	private function typography_css( $bem, $t ) {
		$css  = ".{$bem}__heading,\n.{$bem}__title {\n";
		$css .= "  margin: 0 0 0.5rem;\n";
		$css .= "  font-size: {$t['heading']};\n";
		$css .= "  line-height: 1.2;\n";
		$css .= "}\n\n";

		$css .= ".{$bem}__subtitle {\n";
		$css .= "  margin: 0 0 1rem;\n";
		$css .= "  font-size: clamp(1.125rem, 2.5vw, 1.5rem);\n";
		$css .= "  opacity: 0.85;\n";
		$css .= "}\n\n";

		$css .= ".{$bem}__description {\n";
		$css .= "  margin-bottom: 1.5rem;\n";
		$css .= "  line-height: 1.6;\n";
		$css .= "}\n\n";

		return $css;
	}

	/**
	 * Media (image / gallery / video) CSS.
	 *
	 * @param string $bem Component class.
	 * @param array  $t   Tokens.
	 * @return string
	 */
	private function media_css( $bem, $t ) {
		$css  = ".{$bem}__image { position: relative; overflow: hidden; border-radius: var(--block-radius); }\n";
		$css .= ".{$bem}__image img {\n";
		$css .= "  width: 100%;\n";
		$css .= "  height: auto;\n";
		$css .= "  display: block;\n";
		$css .= "  object-fit: cover;\n";
		$css .= "}\n\n";

		$css .= ".{$bem}__gallery {\n";
		$css .= "  display: grid;\n";
		$css .= "  grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));\n";
		$css .= "  gap: 1rem;\n";
		$css .= "}\n\n";

		$css .= ".{$bem}__video { width: 100%; height: auto; display: block; border-radius: var(--block-radius); }\n\n";

		return $css;
	}

	/**
	 * Button CSS.
	 *
	 * @param string $bem Component class.
	 * @param array  $t   Tokens.
	 * @return string
	 */
	private function button_css( $bem, $t ) {
		$css  = ".{$bem}__button,\n.{$bem} .btn {\n";
		$css .= "  display: inline-block;\n";
		$css .= "  padding: 0.75rem 1.5rem;\n";
		$css .= "  background: var(--block-primary);\n";
		$css .= "  color: #fff;\n";
		$css .= "  text-decoration: none;\n";
		$css .= "  border-radius: 4px;\n";
		$css .= "  font-weight: 600;\n";
		$css .= "  transition: opacity 0.2s ease, transform 0.2s ease;\n";
		$css .= "}\n\n";

		$css .= ".{$bem}__button:hover,\n.{$bem} .btn:hover {\n";
		$css .= "  opacity: 0.9;\n";
		$css .= "  color: #fff;\n";
		$css .= "  transform: translateY(-1px);\n";
		$css .= "}\n\n";

		return $css;
	}

	/**
	 * Repeater / card grid CSS (responsive, no hardcoded column count).
	 *
	 * @param string $bem Component class.
	 * @param array  $t   Tokens.
	 * @return string
	 */
	private function repeater_css( $bem, $t ) {
		$css  = ".{$bem}__items {\n";
		$css .= "  display: grid;\n";
		$css .= "  grid-template-columns: repeat(auto-fit, minmax(min(100%, 260px), 1fr));\n";
		$css .= "  gap: var(--block-gap);\n";
		$css .= "  width: 100%;\n";
		$css .= "}\n\n";

		$css .= ".{$bem}__item {\n";
		$css .= "  display: flex;\n";
		$css .= "  flex-direction: column;\n";
		$css .= "  gap: 0.75rem;\n";
		$css .= "  padding: 1.25rem;\n";
		$css .= "  background: #fff;\n";
		$css .= "  border-radius: var(--block-radius);\n";
		$css .= "  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08);\n";
		$css .= "}\n\n";

		$css .= ".{$bem}__item .{$bem}__image { border-radius: calc(var(--block-radius) - 2px); }\n";
		$css .= ".{$bem}__item h3 { margin: 0; font-size: 1.125rem; font-weight: 600; }\n";
		$css .= ".{$bem}__item p { margin: 0; }\n\n";

		return $css;
	}

	/**
	 * Slider CSS.
	 *
	 * @param string $bem Component class.
	 * @param array  $t   Tokens.
	 * @return string
	 */
	private function slider_css( $bem, $t ) {
		$text    = $t['text'] ?? '#FFFFFF';
		$primary = $t['primary'] ?? '#32CD32';
		$accent  = ! empty( $t['accent'] ) ? $t['accent'] : $primary;
		$css     = '';

		$css .= ".{$bem}__header { text-align: center; max-width: 720px; margin: 0 auto 2.5rem; }\n";
		$css .= ".{$bem}__header:empty { display: none; }\n\n";

		// Horizontal track — each slide is exactly one viewport wide.
		$css .= ".{$bem}__slider {\n";
		$css .= "  position: relative;\n";
		$css .= "  overflow: hidden;\n";
		$css .= "  width: 100%;\n";
		$css .= "}\n";
		$css .= ".{$bem}__track,\n";
		$css .= ".{$bem}__slider .swiper-wrapper {\n";
		$css .= "  display: flex;\n";
		$css .= "  flex-wrap: nowrap;\n";
		$css .= "  align-items: stretch;\n";
		$css .= "  width: 100%;\n";
		$css .= "  transition: transform 0.55s cubic-bezier(0.22, 1, 0.36, 1);\n";
		$css .= "  will-change: transform;\n";
		$css .= "}\n";
		$css .= ".{$bem}__slide,\n";
		$css .= ".{$bem}__slider .swiper-slide {\n";
		$css .= "  flex: 0 0 100%;\n";
		$css .= "  width: 100%;\n";
		$css .= "  min-width: 100%;\n";
		$css .= "  max-width: 100%;\n";
		$css .= "  box-sizing: border-box;\n";
		$css .= "}\n\n";

		// Two-column slide (image | content) — desktop horizontal, mobile stacked.
		$css .= ".{$bem}__slide-inner {\n";
		$css .= "  display: grid;\n";
		$css .= "  grid-template-columns: 1fr;\n";
		$css .= "  gap: 1.75rem;\n";
		$css .= "  align-items: center;\n";
		$css .= "  width: 100%;\n";
		$css .= "  color: {$text};\n";
		$css .= "}\n";
		$css .= "@media (min-width: 768px) {\n";
		$css .= "  .{$bem}__slide-inner {\n";
		$css .= "    grid-template-columns: minmax(0, 1fr) minmax(0, 1fr);\n";
		$css .= "    gap: 3rem;\n";
		$css .= "  }\n";
		$css .= "}\n\n";

		$css .= ".{$bem}__slide-media { margin: 0; min-width: 0; }\n";
		$css .= ".{$bem}__slide-media figure,\n";
		$css .= ".{$bem}__image { margin: 0; overflow: hidden; }\n";
		$css .= ".{$bem}__slide-media img,\n";
		$css .= ".{$bem}__image img {\n";
		$css .= "  width: 100%;\n";
		$css .= "  height: auto;\n";
		$css .= "  display: block;\n";
		$css .= "  object-fit: cover;\n";
		$css .= "  aspect-ratio: 1 / 1;\n";
		$css .= "}\n";
		$css .= ".{$bem}__slide-content {\n";
		$css .= "  display: flex;\n";
		$css .= "  flex-direction: column;\n";
		$css .= "  gap: 1rem;\n";
		$css .= "  min-width: 0;\n";
		$css .= "}\n";
		$css .= ".{$bem}__slide-number {\n";
		$css .= "  margin: 0;\n";
		$css .= "  font-size: 0.875rem;\n";
		$css .= "  letter-spacing: 0.06em;\n";
		$css .= "  opacity: 0.85;\n";
		$css .= "  color: {$text};\n";
		$css .= "}\n";
		$css .= ".{$bem}__title {\n";
		$css .= "  margin: 0;\n";
		$css .= "  font-size: clamp(1.75rem, 3vw, 2.5rem);\n";
		$css .= "  font-weight: 700;\n";
		$css .= "  line-height: 1.2;\n";
		$css .= "  color: {$text};\n";
		$css .= "}\n";
		$css .= ".{$bem}__description {\n";
		$css .= "  margin: 0;\n";
		$css .= "  font-size: 1rem;\n";
		$css .= "  line-height: 1.7;\n";
		$css .= "  color: {$text};\n";
		$css .= "  opacity: 0.92;\n";
		$css .= "}\n";
		$css .= ".{$bem}__focus-heading {\n";
		$css .= "  margin: 0.5rem 0 0;\n";
		$css .= "  font-size: 1.125rem;\n";
		$css .= "  font-weight: 700;\n";
		$css .= "  color: {$text};\n";
		$css .= "}\n";
		$css .= ".{$bem}__focus-areas {\n";
		$css .= "  list-style: none;\n";
		$css .= "  margin: 0.75rem 0 0;\n";
		$css .= "  padding: 0;\n";
		$css .= "  display: flex;\n";
		$css .= "  flex-direction: column;\n";
		$css .= "  gap: 0.85rem;\n";
		$css .= "}\n";
		$css .= ".{$bem}__focus-areas-item {\n";
		$css .= "  display: flex;\n";
		$css .= "  align-items: flex-start;\n";
		$css .= "  gap: 0.75rem;\n";
		$css .= "  margin: 0;\n";
		$css .= "  font-size: 0.975rem;\n";
		$css .= "  line-height: 1.5;\n";
		$css .= "  color: {$text};\n";
		$css .= "}\n";
		$css .= ".{$bem}__focus-areas-item::before {\n";
		$css .= "  content: \"\";\n";
		$css .= "  flex: 0 0 0.7rem;\n";
		$css .= "  width: 0.7rem;\n";
		$css .= "  height: 0.7rem;\n";
		$css .= "  margin-top: 0.35rem;\n";
		$css .= "  background: {$accent};\n";
		$css .= "  clip-path: polygon(0 0, 0 100%, 100% 50%);\n";
		$css .= "}\n\n";

		// Dots.
		$css .= ".{$bem}__dots {\n";
		$css .= "  display: flex;\n";
		$css .= "  justify-content: center;\n";
		$css .= "  align-items: center;\n";
		$css .= "  gap: 0.5rem;\n";
		$css .= "  margin-top: 1.75rem;\n";
		$css .= "}\n";
		$css .= ".{$bem}__dots[hidden] { display: none !important; }\n";
		$css .= ".{$bem}__dot {\n";
		$css .= "  width: 10px;\n";
		$css .= "  height: 10px;\n";
		$css .= "  padding: 0;\n";
		$css .= "  border: 0;\n";
		$css .= "  border-radius: 50%;\n";
		$css .= "  background: rgba(255, 255, 255, 0.35);\n";
		$css .= "  cursor: pointer;\n";
		$css .= "  transition: background 0.2s ease, transform 0.2s ease;\n";
		$css .= "}\n";
		$css .= ".{$bem}__dot.is-active {\n";
		$css .= "  background: {$accent};\n";
		$css .= "  transform: scale(1.15);\n";
		$css .= "}\n\n";

		// Arrows.
		$css .= ".{$bem}__nav {\n";
		$css .= "  display: flex;\n";
		$css .= "  gap: 0.75rem;\n";
		$css .= "  justify-content: center;\n";
		$css .= "  margin-top: 1.25rem;\n";
		$css .= "}\n";
		$css .= ".{$bem}__nav[hidden] { display: none !important; }\n";
		$css .= ".{$bem}__arrow {\n";
		$css .= "  display: inline-flex;\n";
		$css .= "  align-items: center;\n";
		$css .= "  justify-content: center;\n";
		$css .= "  width: 44px;\n";
		$css .= "  height: 44px;\n";
		$css .= "  padding: 0;\n";
		$css .= "  border: 1px solid rgba(255, 255, 255, 0.35);\n";
		$css .= "  border-radius: 50%;\n";
		$css .= "  background: transparent;\n";
		$css .= "  color: {$text};\n";
		$css .= "  cursor: pointer;\n";
		$css .= "  transition: background 0.2s ease, color 0.2s ease, border-color 0.2s ease;\n";
		$css .= "}\n";
		$css .= ".{$bem}__arrow::after { font-family: inherit; font-size: 1.25rem; font-weight: 700; line-height: 1; }\n";
		$css .= ".{$bem}__arrow--prev::after { content: \"\\2039\"; }\n";
		$css .= ".{$bem}__arrow--next::after { content: \"\\203A\"; }\n";
		$css .= ".{$bem}__arrow:hover { background: {$accent}; border-color: {$accent}; color: #001529; }\n\n";

		$css .= ".{$bem}__slider.is-single .{$bem}__nav,\n";
		$css .= ".{$bem}__slider.is-single .{$bem}__dots { display: none !important; }\n\n";

		return $css;
	}

	/**
	 * Accordion CSS.
	 *
	 * @param string $bem Component class.
	 * @param array  $t   Tokens.
	 * @return string
	 */
	private function accordion_css( $bem, $t ) {
		$css  = ".{$bem}__item { border-bottom: 1px solid #e0e0e0; }\n";
		$css .= ".{$bem}__trigger {\n";
		$css .= "  width: 100%;\n";
		$css .= "  text-align: left;\n";
		$css .= "  padding: 1rem 0;\n";
		$css .= "  background: none;\n";
		$css .= "  border: none;\n";
		$css .= "  cursor: pointer;\n";
		$css .= "  font-size: 1rem;\n";
		$css .= "  font-weight: 600;\n";
		$css .= "}\n";
		$css .= ".{$bem}__panel { display: none; padding-bottom: 1rem; }\n";
		$css .= ".{$bem}__panel.is-open { display: block; }\n\n";

		return $css;
	}

	/**
	 * Collect every cell class referenced by the layout structure.
	 *
	 * @param array $spec Block spec.
	 * @return array
	 */
	private function collect_cell_classes( $spec ) {
		$cells = array();

		foreach ( $spec['layout_structure']['rows'] ?? array() as $row ) {
			foreach ( $row['columns'] ?? array() as $column ) {
				if ( ! empty( $column['cell_class'] ) ) {
					foreach ( preg_split( '/\s+/', trim( $column['cell_class'] ) ) as $class ) {
						if ( 0 === strpos( $class, 'cell-' ) ) {
							$cells[ $class ] = $class;
						}
					}
				}
			}
		}

		return array_values( $cells );
	}

	/**
	 * Whether any row defines more than one column.
	 *
	 * @param array $spec Block spec.
	 * @return bool
	 */
	private function structure_has_multiple_columns( $spec ) {
		foreach ( $spec['layout_structure']['rows'] ?? array() as $row ) {
			if ( count( $row['columns'] ?? array() ) > 1 ) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Whether the spec contains a repeater field.
	 *
	 * @param array $fields Fields.
	 * @return bool
	 */
	private function has_repeater( $fields ) {
		foreach ( $fields as $field ) {
			if ( 'repeater' === ( $field['type'] ?? '' ) ) {
				return true;
			}
		}

		return false;
	}

	/**
	 * Sanitise a CSS colour value; fall back when empty/invalid.
	 *
	 * @param string $value    Raw value.
	 * @param string $fallback Fallback colour.
	 * @return string
	 */
	private function css_color( $value, $fallback ) {
		$value = trim( (string) $value );

		if ( '' === $value ) {
			return $fallback;
		}

		if ( preg_match( '/^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/', $value ) ) {
			return $value;
		}

		if ( preg_match( '/^(?:rgb|rgba|hsl|hsla)\([0-9.,%\s\/]+\)$/i', $value ) ) {
			return $value;
		}

		// Named colours / CSS keywords: allow simple word tokens only.
		if ( preg_match( '/^[a-zA-Z]+$/', $value ) ) {
			return strtolower( $value );
		}

		return $fallback;
	}

	/**
	 * Sanitise a generic CSS length/shorthand value.
	 *
	 * @param string $value    Raw value.
	 * @param string $fallback Fallback value.
	 * @return string
	 */
	private function css_value( $value, $fallback ) {
		$value = trim( (string) $value );

		if ( '' === $value ) {
			return $fallback;
		}

		// Block anything that could break out of the declaration.
		if ( preg_match( '/[;{}<>]/', $value ) ) {
			return $fallback;
		}

		return $value;
	}
}
